name: Docs Preview

permissions:
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - closed
    paths:
      - "docs/**"
      - "fortls/interface.py"
  workflow_dispatch:

concurrency: preview-${{github.ref}}

jobs:
  job-name:
    permissions:
      contents: write
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build docs
        run: |
          pip install -e .[dev,docs]
          make -C docs html
      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1.4.8
        with:
          source-dir: docs/_build/html
          preview-branch: gh-pages
          custom-url: fortls.fortran-lang.org
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Build and Deploy
        run: |
          # Commands to build and deploy documentation
          git checkout -b gh-pages
          git add -A
          git commit -m "Deploy preview for PR ${GITHUB_REF##*/} 🛫"
          git push --force origin gh-pages
